In [1]:
import numpy as np
data = np.array([[4.0, 2.0, 0.0, 2.0, 0.0, 2.0],
                [3.5, 2.5, 3.0, 3.5, 2.5, 3.0],
                [3.0, 0.0, 2.5, 5.0, 3.0, 0.0],
                [2.5, 2.5, 0.0, 3.5, 4.0, 0.0],
                [2.5, 2.0, 3.5, 0.0, 3.5, 2.0],
                [0.0, 3.0, 4.0, 3.0, 3.0, 2.0],
                [4.5, 1.5, 3.0, 5.0, 3.5, 0.0]])

In [2]:
def simi(i,j,data):
    items = data[:, [i, j]]
    nn=np.where(items == 0)
    items1=np.delete(items, nn[0], axis=0)
    if items1.size==0:
        return 0
    else:
        return np.corrcoef(items1.T)[0,1]


In [3]:
n1=data.shape[1]#items的数量
simjz=np.ones((n1,n1))
simjz

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [4]:
#对所有items进行循环
for i in range(0,n1):
    for j in range(i+1,n1):
        r1=simi(i,j,data)
        simjz[i,j]=r1
        simjz[j,i]=r1
simjz

array([[ 1.        , -0.63474545, -0.23904572,  0.        , -0.28827833,
         0.18898224],
       [-0.63474545,  1.        ,  0.67419986, -0.44501237, -0.34615385,
         0.17407766],
       [-0.23904572,  0.67419986,  1.        , -0.80311571,  0.15724273,
        -0.8660254 ],
       [ 0.        , -0.44501237, -0.80311571,  1.        ,  0.11720181,
         0.75592895],
       [-0.28827833, -0.34615385,  0.15724273,  0.11720181,  1.        ,
        -0.8660254 ],
       [ 0.18898224,  0.17407766, -0.8660254 ,  0.75592895, -0.8660254 ,
         1.        ]])

In [5]:
user=data[4,:]
user

array([2.5, 2. , 3.5, 0. , 3.5, 2. ])

In [6]:
nn=np.where(user>0)
nn

(array([0, 1, 2, 4, 5], dtype=int64),)

In [7]:
s1=simjz[3,:][nn[0]]
s1

array([ 0.        , -0.44501237, -0.80311571,  0.11720181,  0.75592895])

In [8]:
#norm求数组的L1范数，也就是绝对值的和
sum(user[nn[0]]*s1)/np.linalg.norm(s1, 1)

-0.8385895524944613

In [9]:
#计算用户4所有未评分的商品对其的吸引力
def xiyin(k,data,s1):
    user=data[k,:]
    n1=np.where(user>0)
    n2=np.where(user==0.)#只需要未评分的商品，所以做此过滤
    l1=[]
    for i in n2[0]:
        s2=s1[i,:][n1[0]]
        l1.append(sum(user[n1[0]]*s2)/np.linalg.norm(s2, 1))
    return n2[0],l1

s1=simjz
print(xiyin(0,data,s1))

(array([2, 4], dtype=int64), [-1.14083045359985, -2.0666082304303877])
