In [1]:
import pandas as pd
import numpy as np
import math
from operator import itemgetter
import csv

In [2]:
data=pd.read_csv(r'F:\work\Downloads\词向量.csv')
data

word                                          embedding
0         98  [-0.058803666, 0.05832512, -0.6444828, 0.19280...
1         17  [0.067806736, -0.4460909, -0.79205614, 0.00170...
2      雅马哈r1  [0.6132644, 0.4606244, 0.19470927, 0.251278, -...
3         排气  [0.3676824, -0.30955258, -0.31792253, 0.122256...
4         声浪  [0.35473847, 0.1651163, 0.11610486, -0.0375614...
...      ...                                                ...
33915      ▷  [0.18769372, 0.5005339, -0.23696463, 0.3460938...
33916     川川  [-0.7859129, 0.14881276, 0.51049984, 0.0191508...
33917     徐勇  [-0.3449698, -0.003161303, 0.5403555, 0.435661...
33918     邓昊  [-0.24652152, 0.4843831, -0.18084435, 0.640671...
33919      ░  [-0.0095943445, -0.22507557, -0.004972162, 0.5...

[33920 rows x 2 columns]

In [3]:
word_emb_dict={}
for i in data.index:
    word=data['word'][i]
    embedding=data['embedding'][i].replace('[','').replace(']','').split(', ')
    embedding=[float(x) for x in embedding]
    word_emb_dict[word]=embedding

In [4]:
data=pd.read_csv(r'F:\work\Downloads\全量文章向量.csv')
data

essay_id                                          embedding
0          30400  [0.24455303819968358, 0.042138037637275215, -0...
1          30500  [0.08427137981356764, -0.009691624544941232, -...
2          40940  [0.042010686846873084, 0.026424114100135582, 0...
3          40960  [0.05779453477327912, 0.06266500366454199, 0.1...
4          40980  [-0.007918640299131778, 0.03314927614393807, 0...
...          ...                                                ...
175024   4008594  [0.11051957818199115, -0.09171172327937514, -0...
175025   4008794  [0.10069205265636672, 0.0976819110615539, 0.08...
175026   4008875  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
175027   4008519  [0.18050598225481962, -0.060849764751957, 0.07...
175028   4008979  [0.17216185818060792, -0.148730716001083, 0.04...

[175029 rows x 2 columns]

In [5]:
all_item_dict={}
for i in data.index:
    word=data['essay_id'][i]
    embedding=data['embedding'][i].replace('[','').replace(']','').split(', ')
    embedding=[float(x) for x in embedding]
    all_item_dict[word]=embedding
print('全量文章向量存储成功')
all_matrix=np.zeros((len(all_item_dict.keys()),100))
all_lst=list(all_item_dict.keys())
for i in range(len(all_lst)):
    all_matrix[i]=np.array(all_item_dict[all_lst[i]])
print('全量文章向量矩阵存储成功')


全量文章向量存储成功
全量文章向量矩阵存储成功


In [3]:
data=pd.read_csv(r'F:\work\Downloads\query-impala-543162.csv')
data

essay_id                                          embedding
0        542214  [0.03780527664924443, 0.08105638582516608, 0.0...
1        748854  [0.045289399660649994, 0.11977300958665155, 0....
2        868714  [0.14373190566672625, 0.06701120184615714, 0.0...
3        877834  [0.06701338644409204, 0.0927981458422272, 0.12...
4        881134  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
...         ...                                                ...
13874   3956933  [0.032722054581857785, 0.022579807016360892, 0...
13875   3958473  [0.04209785659659624, 0.052113180939301534, 0....
13876    266974  [0.08183601461871197, 0.01088508058378301, -0....
13877    330914  [0.11022536418094733, 0.07876025058425731, -0....
13878    362434  [0.13833945350623084, 0.05966028299114184, -0....

[13879 rows x 2 columns]

In [4]:
effective_item_dict={}
for i in data.index:
    word=data['essay_id'][i]
    embedding=data['embedding'][i].replace('[','').replace(']','').split(', ')
    embedding=[float(x) for x in embedding]
    effective_item_dict[word]=embedding
print('有效文章向量存储成功')
effective_matrix=np.zeros((len(effective_item_dict.keys()),100))
effective_lst=list(effective_item_dict.keys())
for i in range(len(effective_lst)):
    effective_matrix[i]=np.array(effective_item_dict[effective_lst[i]])
print('有效文章向量矩阵存储成功')


有效文章向量存储成功
有效文章向量矩阵存储成功


In [188]:
data=pd.read_csv(r'F:\work\Downloads\用户向量.csv')
data

motor_user_word_vector_recommend.deviceid  \
0                3923a1f38b588873b37a179845c91b2a   
1                003d506e2fbd4b3daf036d4b6e53fa53   
2                98f64a0d545f313aa2204ef55fddff77   
3                a6511647064636b5a2f4a449e8984f7d   
4                fcf619f817bd1ede3380aaa96e9b9838   
...                                           ...   
1230386          03b19610e0eb4fe7b0acd8c1c508058a   
1230387          0fb2e50e13336fbd535873fc9be0fb5b   
1230388          d933c3d9170d5caa7d59776c149ae038   
1230389          be1c69af7bed8e90d218fd058f75ad44   
1230390          d895d031d34a40609436ce29de3be61c   

        motor_user_word_vector_recommend.user_embedding_kw  \
0        0.06318634731591048,-0.09912425749119262,0.049...   
1        8.807462866835577E-4,-0.04939036209269018,0.06...   
2        0.14718584703805007,0.04232975473318327,-0.026...   
3        -0.002812147688230962,-0.07074115982458448,0.0...   
4        0.1016377091863498,-0.09644624400020585,0.0420...   
...                                                    ...   
1230386  0.19095065356879284,-0.04338922911347161,-0.06...   
1230387  0.1334159013992843,-0.015477231339963768,-0.10...   
1230388  0.04917586196303938,0.007461136442406181,0.039...   
1230389  0.1681357969171669,0.028205787525728634,-0.091...   
1230390  0.1200916867023391,0.05641881540021512,-0.0640...   

         motor_user_word_vector_recommend.user_embedding_q  \
0                                                      NaN   
1                                                      NaN   
2                                                      NaN   
3                                                      NaN   
4                                                      NaN   
...                                                    ...   
1230386  0.007858249975053955,0.017652916115536075,0.03...   
1230387                                                NaN   
1230388                                                NaN   
1230389                                                NaN   
1230390  0.14644997128173357,-0.04839127201675632,0.070...   

         motor_user_word_vector_recommend.p_day  
0                                      20210131  
1                                      20210131  
2                                      20210131  
3                                      20210131  
4                                      20210131  
...                                         ...  
1230386                                20210131  
1230387                                20210131  
1230388                                20210131  
1230389                                20210131  
1230390                                20210131  

[1230391 rows x 4 columns]

In [192]:
user_emb_dict={}
for i in range(10000):
    word=data['motor_user_word_vector_recommend.deviceid'][i]
    embedding=data['motor_user_word_vector_recommend.user_embedding_kw'][i].split(',')
    embedding=[float(x) for x in embedding]
    user_emb_dict[word]=embedding
print('有行为的文章向量存储成功')

有行为的文章向量存储成功


In [8]:
data=pd.read_csv(r'F:\work\Downloads\行为文章向量.csv')
data

essay_id                                          embedding
0         43580  [0.035957464605007816, 0.0015200319848479857, ...
1         44320  [0.17440808297898744, -0.012258827973403103, 0...
2         44520  [0.05477280770991924, 0.022277350122481405, -0...
3         44540  [0.055196404878373795, 0.09817645805332503, -0...
4         44960  [0.12462135727206117, -0.044895377377132444, -...
...         ...                                                ...
44041   4008594  [0.11051957818199115, -0.09171172327937514, -0...
44042   4008794  [0.10069205265636672, 0.0976819110615539, 0.08...
44043   4008875  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
44044   4008519  [0.18050598225481962, -0.060849764751957, 0.07...
44045   4008979  [0.17216185818060792, -0.148730716001083, 0.04...

[44046 rows x 2 columns]

In [9]:
act_item_dict={}
for i in data.index:
    word=data['essay_id'][i]
    embedding=data['embedding'][i].replace('[','').replace(']','').split(', ')
    embedding=[float(x) for x in embedding]
    act_item_dict[word]=embedding
print('有行为的文章向量存储成功')
act_matrix=np.zeros((len(act_item_dict.keys()),100))
act_lst=list(act_item_dict.keys())
for i in range(len(act_lst)):
    act_matrix[i]=np.array(act_item_dict[act_lst[i]])
print('有行为的文章向量矩阵存储成功')

有行为的文章向量存储成功
有行为的文章向量矩阵存储成功


In [10]:
sim_matrix=np.dot(act_matrix,effective_matrix.T)
print('相似度矩阵计算成功')

相似度矩阵计算成功


In [11]:
sim_matrix

array([[0.51798637, 0.39421068, 0.37146896, ..., 0.        , 0.5073194 ,
        0.28707017],
       [0.3826785 , 0.2993802 , 0.37521444, ..., 0.        , 0.4565371 ,
        0.34761973],
       [0.51648411, 0.42265124, 0.34657656, ..., 0.        , 0.53061932,
        0.46102136],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.43238191, 0.32123662, 0.34840745, ..., 0.        , 1.        ,
        0.34273234],
       [0.58479878, 0.42132335, 0.25427454, ..., 0.        , 0.34273234,
        1.        ]])

In [12]:
output={}
for i in range(len(act_lst)):
    act_item=act_lst[i]
    output.setdefault(act_item,{})
    act_tensor=sim_matrix[i]
    sorted_list=sorted(enumerate(list(act_tensor)), key=itemgetter(1),reverse=True)
    for j,sim in sorted_list[1:11]:
        sim_item=effective_lst[j]
        output[act_item][sim_item]=sim
print('相似度获取成功!')

相似度获取成功!


In [18]:
titles=pd.read_csv(r'F:\work\Downloads\全量文章标题.csv')
titles

essay_id                       e.c_title
0          30143                       雅马哈赛鹰GT踏板
1          30283   这个杀手有点冷 Kawasaki Z1000 ABS 测评
2          30400                  国内贩售版CBR300R加速
3          30401                  五羊本田CB190R加速测试
4          30415                Honda X-Adv 国内首试
...          ...                             ...
171715   4008585                     北京将要扩大禁摩范围了
171716   4008594  2021KTM390ADVENTURE强劲的小排量旅行耐力车
171717   4008794        骑者没有春夏秋冬之分，只有一颗炽热的心，敬骑士！
171718   4008875                          你们怎么看？
171719   4008979               铃木gsx250防摔棒牛角安装实录

[171720 rows x 2 columns]

In [19]:
title_dict={}
for i in titles.index:
    itemid=titles['essay_id'][i]
    title=titles['e.c_title'][i]
    title_dict[itemid]=title

In [31]:
keywords=pd.read_csv(r'F:\work\Downloads\文章关键词.csv')
keywords

essay_id                                        kw_keywords
0          30400  {'cbr300': 0.9790462842829708, '贩售': 0.8909096...
1          30500  {'阿普利亚rsv4rr': 0.8897654637573761, '评测': 0.805...
2          40940  {'mm': 1.0, 'k1600': 0.5555224424064236, '系统':...
3          40960  {'屹立': 0.8645441910035089, '不倒': 0.46613634108...
4          40980  {'混血儿': 0.9477826822877973, '车界': 0.5522649362...
...          ...                                                ...
348888   4009795  {'极客飒155': 0.9962486185648347, '民用': 0.8580776...
348889   4009058  {'新车': 0.7350253692086189, 'ness': 0.602315013...
348890   4011098                                        {'好看': 1.0}
348891   4009759  {'adv': 0.891526017391374, '未上市': 0.8760596663...
348892   4009779  {'机滤': 0.9139967971529752, '出奇': 0.76244566791...

[348893 rows x 2 columns]

In [32]:
keywords_dict={}
for i in keywords.index:
    itemid=keywords['essay_id'][i]
    kw=eval(keywords['kw_keywords'][i])
    keywords_dict[itemid]=kw

In [105]:
user_kw=pd.read_csv(r'F:\work\Downloads\用户关键词.csv')
user_kw=user_kw.dropna()
user_kw_dict={}
for i in user_kw.index:
    deviceid=user_kw['device_id'][i]
    kw=user_kw['u_dy_rt_keywords'][i].split(',')
    user_kw_dict[deviceid]=kw

In [141]:
user_emb_dict={}
for i in user_kw_dict.keys():
    user_emb=np.zeros((1,100))[0]
    for word in user_kw_dict[i]:
        if word in word_emb_dict.keys():
            user_emb=user_emb+np.array(word_emb_dict[word])
    x=np.linalg.norm(user_emb)
    user_emb=user_emb/x
    user_emb_dict[i]=user_emb

D:\anaconda\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide
  


In [38]:
import hnswlib
num_elements=effective_matrix.shape[0]
dim=effective_matrix.shape[1]
p=hnswlib.Index(space='l2',dim=dim)
p.init_index(max_elements=num_elements,ef_construction=100,M=128)
p.set_ef(10)
p.set_num_threads(4)
p.add_items(effective_matrix)

In [98]:
#i2i
i=74
item1=act_lst[i]
print(title_dict[item1])
print(list(keywords_dict[item1].keys()))
print('----------------------------------------------')
sim_dict=output[item1]
for k,v in sim_dict.items():
    print(title_dict[k])
    print(list(keywords_dict[k].keys()))
    print('----------------------')

比亚乔贝佛利来了 你是否愿意花6万买个小众踏板车？
['佛利', '踏板车', '比亚乔', '欧系', '国内', '轮圈', '消费者', 'asr', 'medley', 'abs', '引进', '典型', 'beverly300', '日系', '分为', '支撑', '座垫']
----------------------------------------------
骑意式优雅style踏板是怎样的体验?
['踏板', '踏板车', '比亚乔', 'fly150', '空间', '减震', '该车', '优雅', 'cbs', '通勤', '常见', '运行', '充裕', '制动', '钥匙', '高端', '座椅']
----------------------
欧系踏板旗舰代表 比亚乔Beverly 300S
['beverly300s', '比亚乔', '欧系', '踏板', '踏板车', '体验', 'asr', '配合', '车款', '经典', '驾控', '引擎', '空间', '山路', '核心', '日系', '关键']
----------------------
售6万元的踏板究竟有何优势?标配ABS、ASR,水冷引擎马力21匹
['abs', '踏板', '该车', '大轮', 'asr', '水冷', '万元', '21', '马力', '一款', '信息', '有何', '踏板车', '显示', '标配', '引擎', '佛利', '优势', '车灯', '眼中', '体现']
----------------------
解析欧系运动大羊,颜值和实力并存,标配ABS系统,售价26800元
['踏板车', 'srmax250', '运动', '外观', 'abs', '大羊', 'srmax', '出色', '车型', '欧系', '款车', '标配', '配备', '颜值', '出厂', '踏板', '售价', '调节', '轮毂']
----------------------
比亚乔发布2021款Beverly，双动力、双版本登场
['beverly', '版本', '比亚乔', '动力', '老款', 'cc', '2021', '行灯', '新款', '系统', 'led', '相比', 'pe', '大轮',

In [217]:
#i2u
user_list=list(user_kw_dict.keys()&user_emb_dict.keys())
i=2
user=user_list[i]
print(user)
print(user_kw_dict[user])
user_emb=np.zeros((1,100))[0]
for word in user_kw_dict[user]:
    if word in word_emb_dict.keys():
        user_emb=user_emb+np.array(word_emb_dict[word])
x=np.linalg.norm(user_emb)
user_emb=user_emb/x
user_emb=user_emb_dict[user]
sim_matrix=np.dot(user_emb,effective_matrix.T)
sorted_list=sorted(enumerate(list(sim_matrix)), key=itemgetter(1),reverse=True)
for j,sim in sorted_list[:10]:
    simitem=effective_lst[j]
    if simitem in title_dict.keys():
        title=title_dict[simitem]
        print(title)

4355bfba580e7d760b8d5fb4ee31f8d1
['巡航', '太子', '魔枭', '哈雷', 'cm300', '美式', 'gv300s', '金吉拉', '设计', 'cc', '川崎小火神', '平民', '哈雷883', '轻骑gv250', '国产', '摩友', '轻松', '风格', '价格', '国内', '新车', '妹子', '双缸', '不俗', '座椅', '车头', 'ke', '26', '舒适度', '10']
纯正太子车价格26800,外观超帅,动力不俗!轻骑GV250!
入门级经济太子车,极速110续航500公里,油耗低至冰点,仅1.75L
仅售26800元,国产中量级巡航,搭配V缸发动机,充满浓烈美式风
V型发动机、座高710、提速8秒，2.8W圆你的哈雷梦
国产巡航车又一搅局者，跨界风格、皮带传动，19980元起
纯正美式巡航，解读轻骑骁胜巡风GV650
大排量巡航太子,90度V型双缸引擎,极速160km,售价59800元!
入门级经济太子车,极速110续航500公里,油耗低至冰点,仅1.75L
运动巡航太子车，售价不到3万，动力强劲配ABS，配17L油箱
终于有一款优质太子车了,30马力300水冷V缸ABS,不足3w


In [41]:
user_emb=[0.050383161075704744, 0.04837009918561921, -0.06836901466395846, 0.05322148825972053, -0.06091031188291118, 0.12312081061149334, 0.18701551480148598, -0.014350025591708478, -0.03503858772094277, -0.05812972757307398, -0.04497475896952169, 0.0546346552893759, 0.05896629110635191, -0.0971989442291756, 0.061057013339785825, 0.0688068112197787, -0.1382093314166505, -0.06720528275419316, -0.01547941757071371, 0.024003524326340984, -0.13993632701247516, -0.007358403978648096, 0.08671697975088272, 0.12627430089508332, 0.03190814907148095, -0.021655389600734844, 0.07029810590042342, -0.19448076762273003, -0.01850177448082471, 0.14270393386874658, 0.10817295161575663, 0.14381593161889394, -0.05743096013758382, -0.11488225975738434, -0.16318309688023805, 0.04321473146243316, 0.0905899879177645, 0.13146265854917777, -0.09771616540801942, -0.19070133919188265, 0.14024093536689167, -0.10123920986540318, 0.016865500642625104, -0.001975762344266076, -0.12005887727365266, 0.013229283775418835, -0.12726218151484325, -0.10990207163851642, -0.018641432075952917, -0.042081180113999556, -0.11454766748645906, -0.1551793090117885, -0.04200419808481559, 0.04973634433008694, 0.01742055495970112, 0.1578296426403574, 0.16210356209706353, 0.1389394913200495, -0.22360665648439426, 0.05985169767845251, 0.053784192944204647, 0.040095498253638555, 0.12248139235115091, 0.04809374029618359, 0.09099974711987352, 0.002586800779576468, 0.05200390218238696, 0.0978059426076468, 0.01421927335566716, -0.028293824959643114, 0.004000620714233747, -0.0957256270833803, -0.013230578537960681, -0.04339774813626653, 0.030432282171465003, 0.14703371923584407, 0.02784163908461845, -0.07491690060564826, 0.07298344120272388, -0.04420842304718467, -0.0037945645584803716, -0.15789230053036252, 0.09528685614141508, -0.09371119972699635, -0.00046228325525716563, 0.25715139977047174, -0.04545575441584867, -0.26216705024223497, 0.07745371935307385, 0.0534678510804392, -0.13434020753739426, 0.06616704780281424, 0.05544924873505166, 0.06679475354398544, 0.057225003408988104, -0.08114043858788937, 0.008035627758567802, 0.15878224650458297, 0.12525034036930444, -0.14172034518795854]

In [42]:
np.linalg.norm(user_emb)

1.0

In [47]:
p.knn_query(user_emb,10)

(array([[10052,   454, 12114,   173,  3295,  9986, 11561,  1142, 13580,
         13264]], dtype=uint64),
 array([[0.        , 0.21584232, 0.2525617 , 0.25956547, 0.3103227 ,
         0.3115612 , 0.32505172, 0.33015794, 0.33419982, 0.3377743 ]],
       dtype=float32))

In [46]:
for i in p.knn_query(user_emb,10)[0].tolist()[0]:
    itemid=effective_lst[i]
    print(itemid)
    if itemid in title_dict.keys():
        print(title_dict[itemid])

3914188
外卖小哥喜提铃木uy
3782734
摩友评价很高的,五款小巧摩托车,送快递外卖省油耐用,外观拉风
3611070
不到8千，又一款外卖、拉货利器：解析豪爵EH150，实用为主
3059954
想进入外卖行业，1万内的跨骑车，求推荐
3585697
兼职送外卖，UU和USR都在做活动，价格有点心动，如何选？
3824548
6千多元的外卖、代步利器！解析本田喜蕴100：2.2升油耗
3461369
国四铃木丽至110测评（真实车主）
3952800
这技术不送外卖可惜了😂
3420053
六千拿下铃木UZ110T，对比UU，虽没那么省油，但强大
3871092
闪送外卖都骑什么摩托车？


In [220]:
len(data)

1230391

In [45]:
title_dict[3824548]

'6千多元的外卖、代步利器！解析本田喜蕴100：2.2升油耗'

In [169]:
def test_hnsw_time(emb,path):
    p= hnswlib.Index(space='l2', dim=dim)
    p.load_index('model.bin')
    emb=emb.replace('[','').replace(']','').split(', ')
    emb=[float(x) for x in emb]
    return p.knn_query(emb,10)

In [172]:
def test_time(sql):
    m = timeit.repeat(sql, repeat=10, number=1, globals=globals())
    m = np.array(m) * 1000.0 #换算为毫秒
    print(np.min(m), np.mean(m), np.max(m), np.std(m))

In [175]:
import timeit
emb=data['embedding'][0]
test_time("test_hnsw_time(emb,'model.bin')")

61.34800000290852 64.3564800004242 68.45109999994747 1.816563572008957


In [176]:
p.knn_query(user_emb,10)[0]

array([[ 3148,  8178,  3029,  2823,  6511,  4348, 10356,   444,  9142,
         2526]], dtype=uint64)

In [167]:
p.save_index('model.bin')

In [178]:
def load(path):
    q = hnswlib.Index(space='l2', dim=dim)
    q.load_index(path)

In [182]:
q = hnswlib.Index(space='l2', dim=dim)
q.load_index('model.bin')

In [187]:
test_time("load('model.bin')")

63.384599998244084 67.47562999953516 75.23519999813288 4.023035528957869


In [227]:
a={'cbr300': 0.9790462842829708, '贩售': 0.8909096790577531, '加速': 0.6249048569763798, '国内': 0.5022938587331897, '超清': 0.1697070890458812}


{'cbr300': 0.9790462842829708,
 '贩售': 0.8909096790577531,
 '加速': 0.6249048569763798,
 '国内': 0.5022938587331897,
 '超清': 0.1697070890458812}

In [231]:
import json
a={'cbr300': 0.9790462842829708, '贩售': 0.8909096790577531, '加速': 0.6249048569763798, '国内': 0.5022938587331897, '超清': 0.1697070890458812}
b=json.dumps(a,ensure_ascii=False)
eval(b)

'{"cbr300": 0.9790462842829708, "贩售": 0.8909096790577531, "加速": 0.6249048569763798, "国内": 0.5022938587331897, "超清": 0.1697070890458812}'

In [232]:
eval(b)

{'cbr300': 0.9790462842829708,
 '贩售': 0.8909096790577531,
 '加速': 0.6249048569763798,
 '国内': 0.5022938587331897,
 '超清': 0.1697070890458812}