In [2]:
import numpy as np
np.__version__

'1.15.4'

In [10]:
data=np.array([1,2,3,4,5])
data?

In [13]:
new_data=data.astype(np.float)
new_data.size

5

In [6]:
import numpy as np
np.zeros((2,10),dtype=int,order='F')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.diag([1,2,3,4],k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [9]:
de=np.arange(16).reshape((4,4))
de

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
my_type=np.dtype({'names':['book','version'],'formats':['S40',np.int]})
my_books=np.array([("learn python",2),('learn sata',1)],dtype=my_type)
my_books['book']

array([b'learn python', b'learn sata'], dtype='|S40')

In [22]:
np.fromfunction(lambda i,j:i+j,(9,9),dtype=float)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16.]])